from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from pydantic import BaseModel

from project_pipeline.configuration.models import RuntimeSettings, SecretReference
from project_pipeline.contracts.diagnostics import DiagnosticSnapshot
from project_pipeline.contracts.envelopes import (
    ActionIntent,
    CommandEnvelope,
    CommandResult,
    EventEnvelope,
    StateTransition,
)
from project_pipeline.contracts.errors import AdapterErrorPayload
from project_pipeline.domain import (
    AdapterQualificationReport,
    AdmissionDecision,
    AgentRegistrySnapshot,
    AgentSpec,
    BackpressureDecision,
    BackpressurePolicy,
    BackpressureSignals,
    BootstrapPlan,
    BootstrapReceipt,
    BuildSequence,
    CapabilityRoutePolicy,
    CapabilitySpec,
    CircuitBreakerPolicy,
    CircuitBreakerRecord,
    CompiledProjectManifest,
    CompiledRepositoryMap,
    CompletionProjection,
    ConflictEdge,
    ContextCandidate,
    ContextItem,
    ContextPack,
    ContextPolicy,
    ContextReceipt,
    ContextSelection,
    ContextTelemetry,
    ControlSnapshot,
    CoverageReport,
    CriticalPathAnalysis,
    DelegationEnvelope,
    DomainStateTransition,
    ExecutionAttempt,
    ExecutionReceipt,
    ExecutionTaskContract,
    FirewallResult,
    JiraAdapterCapabilities,
    JiraCommentIntent,
    JiraMirrorBundle,
    JiraProjectMetadata,
    JiraReconciliationPlan,
    JiraRemoteSnapshot,
    JiraStatusMapping,
    JiraSyncConflict,
    JiraSyncOperation,
    JiraSyncReceipt,
    JiraTransitionReadiness,
    LaneAssignment,
    LeaseBundle,
    LocalJiraIssue,
    ModelSpec,
    NormalizedUsage,
    PerformanceObservation,
    PerformanceSummary,
    ProjectGapReport,
    ProjectIntakeRequest,
    ProjectManifest,
    ProjectProfileDetection,
    ProjectStateRecord,
    ProviderInvocationResult,
    ProviderSpec,
    ProviderStateObservation,
    QualificationCheckResult,
    RemoteJiraIssue,
    RepositoryDiscovery,
    RequirementRecord,
    ResourceClaim,
    ResourceLease,
    ResourcePool,
    ResourceRegistrySnapshot,
    ReviewerPackage,
    RouteCandidate,
    RoutingDecision,
    SchedulerPlan,
    SchedulerSimulationResult,
    SchedulerTaskProfile,
    ScopeReconciliationReport,
    SequenceItem,
    SequenceScore,
    TaskControlFact,
    TaskEligibility,
    TaskReadiness,
    TaskStateRecord,
    ToolSpec,
    TraceabilityLink,
    TraceabilityMutation,
    TraceabilityMutationResult,
)
from project_pipeline.domain.assurance import (
    AcceptanceCriterion,
    AssuranceSimulationResult,
    AttemptBudget,
    AttemptObservation,
    CandidateCompletionAssessment,
    CompletionFailure,
    CompletionGateDecision,
    CompletionGateFacts,
    CompletionQuestionResult,
    DeliveryGateDecision,
    EvidenceAssessment,
    IndependentReview,
    LoopGuardDecision,
    ProgressDelta,
    ReviewerIdentity,
    ScopeChangeDecision,
    ScopeContract,
    TruthRecord,
    VerificationPlan,
)
from project_pipeline.domain.budget import (
    BudgetAdmissionDecision,
    BudgetAdmissionRequest,
    BudgetAnomaly,
    BudgetChangeImpact,
    BudgetForecast,
    BudgetLedgerEntry,
    BudgetLimit,
    BudgetPolicy,
    BudgetSimulationResult,
    BudgetSnapshot,
    CostHistoryObservation,
    CostOutcomeMetrics,
    InfracostEstimate,
    QuotaLimit,
    SpendLease,
)
from project_pipeline.domain.github import (
    BranchGuardianDecision,
    GitBranch,
    GitHubAdapterCapabilities,
    GitHubBranchProtection,
    GitHubOperation,
    GitHubOperationReceipt,
    GitHubRepositoryMetadata,
    GitRepositorySnapshot,
    GitWorktree,
    MergeGateDecision,
    PullRequestCheck,
    PullRequestReview,
    PullRequestSnapshot,
    ResourceOwnershipClaim,
)
from project_pipeline.domain.orchestration import (
    BackendCapabilities as OrchestrationBackendCapabilities,
)
from project_pipeline.domain.orchestration import (
    BackendMutationReceipt,
    BackendRunObservation,
    DurableOperation,
    DurableWait,
    OrchestrationPolicy,
    OrchestrationSimulationResult,
    OrchestrationStatus,
    RecoveryDecision,
    RetryPolicy,
    WorkerHeartbeat,
    WorkflowCheckpoint,
    WorkflowDefinition,
    WorkflowEvent,
    WorkflowInstance,
    WorkflowSignal,
    WorkflowStartRequest,
    WorkflowStepDefinition,
)
from project_pipeline.domain.security import (
    ApprovalRecord,
    ArtifactIntegrityRecord,
    CapabilityGrant,
    EgressDecision,
    EgressRequest,
    PolicyDecision,
    ReleaseProvenance,
    RoleDefinition,
    RootOfTrust,
    SBOMComponent,
    SecretCapabilityReference,
    SecretLease,
    SecurityAuditEvent,
    SecurityIdentity,
    SelfModificationAssessment,
    SoftwareBillOfMaterials,
    SupplyChainFinding,
    SupplyChainGateResult,
)
from project_pipeline.domain.verification import (
    AccessibilityEvidence,
    BrowserEvidence,
    FaultScenarioResult,
    GoldenJourneyDefinition,
    GoldenJourneyResult,
    MutationProbeResult,
    PerformanceResult,
    PostMergeReport,
    PropertyProbeResult,
    VerificationArtifact,
    VerificationCheckResult,
    VerificationCheckSpec,
    VerificationImpactSet,
    VerificationPortfolioSnapshot,
    VerificationRun,
    VerificationToolActivation,
)
from project_pipeline.persistence.migrations import MigrationCatalog, MigrationRecord

SCHEMA_MODELS: dict[str, type[BaseModel]] = {
    "security_identity.schema.json": SecurityIdentity,
    "security_role.schema.json": RoleDefinition,
    "security_capability_grant.schema.json": CapabilityGrant,
    "security_approval.schema.json": ApprovalRecord,
    "security_policy_decision.schema.json": PolicyDecision,
    "security_egress_request.schema.json": EgressRequest,
    "security_egress_decision.schema.json": EgressDecision,
    "security_secret_reference.schema.json": SecretCapabilityReference,
    "security_secret_lease.schema.json": SecretLease,
    "security_audit_event.schema.json": SecurityAuditEvent,
    "security_sbom_component.schema.json": SBOMComponent,
    "security_sbom.schema.json": SoftwareBillOfMaterials,
    "security_supply_chain_finding.schema.json": SupplyChainFinding,
    "security_integrity.schema.json": ArtifactIntegrityRecord,
    "security_release_provenance.schema.json": ReleaseProvenance,
    "security_supply_chain_gate.schema.json": SupplyChainGateResult,
    "security_self_modification.schema.json": SelfModificationAssessment,
    "security_root_of_trust.schema.json": RootOfTrust,
    "verification_tool_activation.schema.json": VerificationToolActivation,
    "verification_check_spec.schema.json": VerificationCheckSpec,
    "verification_artifact.schema.json": VerificationArtifact,
    "verification_check_result.schema.json": VerificationCheckResult,
    "verification_run.schema.json": VerificationRun,
    "verification_golden_journey.schema.json": GoldenJourneyDefinition,
    "verification_golden_journey_result.schema.json": GoldenJourneyResult,
    "verification_test_impact.schema.json": VerificationImpactSet,
    "verification_browser_evidence.schema.json": BrowserEvidence,
    "verification_accessibility_evidence.schema.json": AccessibilityEvidence,
    "verification_performance_result.schema.json": PerformanceResult,
    "verification_property_probe.schema.json": PropertyProbeResult,
    "verification_mutation_probe.schema.json": MutationProbeResult,
    "verification_fault_scenario.schema.json": FaultScenarioResult,
    "verification_post_merge_report.schema.json": PostMergeReport,
    "verification_portfolio_snapshot.schema.json": VerificationPortfolioSnapshot,
    "assurance_acceptance_criterion.schema.json": AcceptanceCriterion,
    "assurance_verification_plan.schema.json": VerificationPlan,
    "assurance_truth_record.schema.json": TruthRecord,
    "assurance_evidence_assessment.schema.json": EvidenceAssessment,
    "assurance_reviewer_identity.schema.json": ReviewerIdentity,
    "assurance_independent_review.schema.json": IndependentReview,
    "assurance_attempt_observation.schema.json": AttemptObservation,
    "assurance_attempt_budget.schema.json": AttemptBudget,
    "assurance_loop_guard_decision.schema.json": LoopGuardDecision,
    "assurance_progress_delta.schema.json": ProgressDelta,
    "assurance_delivery_gate_decision.schema.json": DeliveryGateDecision,
    "assurance_scope_contract.schema.json": ScopeContract,
    "assurance_scope_change_decision.schema.json": ScopeChangeDecision,
    "assurance_candidate_completion.schema.json": CandidateCompletionAssessment,
    "assurance_completion_question_result.schema.json": CompletionQuestionResult,
    "assurance_completion_failure.schema.json": CompletionFailure,
    "assurance_completion_gate_facts.schema.json": CompletionGateFacts,
    "assurance_completion_gate_decision.schema.json": CompletionGateDecision,
    "assurance_simulation_result.schema.json": AssuranceSimulationResult,
    "budget_admission_decision.schema.json": BudgetAdmissionDecision,
    "budget_admission_request.schema.json": BudgetAdmissionRequest,
    "budget_anomaly.schema.json": BudgetAnomaly,
    "budget_change_impact.schema.json": BudgetChangeImpact,
    "budget_forecast.schema.json": BudgetForecast,
    "budget_ledger_entry.schema.json": BudgetLedgerEntry,
    "budget_limit.schema.json": BudgetLimit,
    "budget_policy.schema.json": BudgetPolicy,
    "budget_simulation_result.schema.json": BudgetSimulationResult,
    "budget_snapshot.schema.json": BudgetSnapshot,
    "budget_cost_history.schema.json": CostHistoryObservation,
    "budget_outcome_metrics.schema.json": CostOutcomeMetrics,
    "budget_infracost_estimate.schema.json": InfracostEstimate,
    "budget_quota_limit.schema.json": QuotaLimit,
    "budget_spend_lease.schema.json": SpendLease,
    "orchestration_backend_capabilities.schema.json": OrchestrationBackendCapabilities,
    "orchestration_backend_mutation_receipt.schema.json": BackendMutationReceipt,
    "orchestration_backend_run_observation.schema.json": BackendRunObservation,
    "orchestration_checkpoint.schema.json": WorkflowCheckpoint,
    "orchestration_definition.schema.json": WorkflowDefinition,
    "orchestration_event.schema.json": WorkflowEvent,
    "orchestration_operation.schema.json": DurableOperation,
    "orchestration_policy.schema.json": OrchestrationPolicy,
    "orchestration_recovery_decision.schema.json": RecoveryDecision,
    "orchestration_retry_policy.schema.json": RetryPolicy,
    "orchestration_simulation_result.schema.json": OrchestrationSimulationResult,
    "orchestration_start_request.schema.json": WorkflowStartRequest,
    "orchestration_status.schema.json": OrchestrationStatus,
    "orchestration_step_definition.schema.json": WorkflowStepDefinition,
    "orchestration_wait.schema.json": DurableWait,
    "orchestration_worker_heartbeat.schema.json": WorkerHeartbeat,
    "orchestration_workflow_instance.schema.json": WorkflowInstance,
    "orchestration_workflow_signal.schema.json": WorkflowSignal,
    "context_candidate.schema.json": ContextCandidate,
    "context_item.schema.json": ContextItem,
    "context_pack.schema.json": ContextPack,
    "context_policy.schema.json": ContextPolicy,
    "context_receipt.schema.json": ContextReceipt,
    "context_selection.schema.json": ContextSelection,
    "context_telemetry.schema.json": ContextTelemetry,
    "context_coverage.schema.json": CoverageReport,
    "delegation_envelope.schema.json": DelegationEnvelope,
    "context_firewall_result.schema.json": FirewallResult,
    "context_reviewer_package.schema.json": ReviewerPackage,
    "agent_adapter_qualification.schema.json": AdapterQualificationReport,
    "agent_registry_snapshot.schema.json": AgentRegistrySnapshot,
    "agent_spec.schema.json": AgentSpec,
    "agent_capability_route_policy.schema.json": CapabilityRoutePolicy,
    "agent_capability_spec.schema.json": CapabilitySpec,
    "agent_circuit_breaker_policy.schema.json": CircuitBreakerPolicy,
    "agent_circuit_breaker_record.schema.json": CircuitBreakerRecord,
    "agent_execution_attempt.schema.json": ExecutionAttempt,
    "agent_execution_receipt.schema.json": ExecutionReceipt,
    "agent_execution_task_contract.schema.json": ExecutionTaskContract,
    "agent_model_spec.schema.json": ModelSpec,
    "agent_normalized_usage.schema.json": NormalizedUsage,
    "agent_performance_observation.schema.json": PerformanceObservation,
    "agent_performance_summary.schema.json": PerformanceSummary,
    "agent_provider_invocation_result.schema.json": ProviderInvocationResult,
    "agent_provider_spec.schema.json": ProviderSpec,
    "agent_provider_state.schema.json": ProviderStateObservation,
    "agent_qualification_check.schema.json": QualificationCheckResult,
    "agent_route_candidate.schema.json": RouteCandidate,
    "agent_routing_decision.schema.json": RoutingDecision,
    "agent_tool_spec.schema.json": ToolSpec,
    "scheduler_admission_decision.schema.json": AdmissionDecision,
    "scheduler_backpressure_decision.schema.json": BackpressureDecision,
    "scheduler_backpressure_policy.schema.json": BackpressurePolicy,
    "scheduler_backpressure_signals.schema.json": BackpressureSignals,
    "scheduler_conflict_edge.schema.json": ConflictEdge,
    "scheduler_lane_assignment.schema.json": LaneAssignment,
    "scheduler_lease_bundle.schema.json": LeaseBundle,
    "scheduler_plan.schema.json": SchedulerPlan,
    "scheduler_resource_claim.schema.json": ResourceClaim,
    "scheduler_resource_lease.schema.json": ResourceLease,
    "scheduler_resource_pool.schema.json": ResourcePool,
    "scheduler_resource_registry.schema.json": ResourceRegistrySnapshot,
    "scheduler_simulation_result.schema.json": SchedulerSimulationResult,
    "scheduler_task_profile.schema.json": SchedulerTaskProfile,
    "control_build_sequence.schema.json": BuildSequence,
    "control_completion_projection.schema.json": CompletionProjection,
    "control_critical_path.schema.json": CriticalPathAnalysis,
    "control_scope_reconciliation.schema.json": ScopeReconciliationReport,
    "control_sequence_item.schema.json": SequenceItem,
    "control_sequence_score.schema.json": SequenceScore,
    "control_snapshot.schema.json": ControlSnapshot,
    "control_task_fact.schema.json": TaskControlFact,
    "control_task_eligibility.schema.json": TaskEligibility,
    "control_task_readiness.schema.json": TaskReadiness,
    "github_adapter_capabilities.schema.json": GitHubAdapterCapabilities,
    "github_branch.schema.json": GitBranch,
    "github_branch_protection.schema.json": GitHubBranchProtection,
    "github_branch_guardian_decision.schema.json": BranchGuardianDecision,
    "github_merge_gate_decision.schema.json": MergeGateDecision,
    "github_operation.schema.json": GitHubOperation,
    "github_operation_receipt.schema.json": GitHubOperationReceipt,
    "github_pull_request.schema.json": PullRequestSnapshot,
    "github_pull_request_check.schema.json": PullRequestCheck,
    "github_pull_request_review.schema.json": PullRequestReview,
    "github_repository_metadata.schema.json": GitHubRepositoryMetadata,
    "github_repository_snapshot.schema.json": GitRepositorySnapshot,
    "github_resource_ownership.schema.json": ResourceOwnershipClaim,
    "github_worktree.schema.json": GitWorktree,
    "jira_adapter_capabilities.schema.json": JiraAdapterCapabilities,
    "jira_comment_intent.schema.json": JiraCommentIntent,
    "jira_local_issue.schema.json": LocalJiraIssue,
    "jira_mirror_bundle.schema.json": JiraMirrorBundle,
    "jira_project_metadata.schema.json": JiraProjectMetadata,
    "jira_reconciliation_plan.schema.json": JiraReconciliationPlan,
    "jira_remote_issue.schema.json": RemoteJiraIssue,
    "jira_remote_snapshot.schema.json": JiraRemoteSnapshot,
    "jira_status_mapping.schema.json": JiraStatusMapping,
    "jira_sync_conflict.schema.json": JiraSyncConflict,
    "jira_sync_operation.schema.json": JiraSyncOperation,
    "jira_sync_receipt.schema.json": JiraSyncReceipt,
    "jira_transition_readiness.schema.json": JiraTransitionReadiness,
    "action_intent.schema.json": ActionIntent,
    "adapter_error.schema.json": AdapterErrorPayload,
    "command_envelope.schema.json": CommandEnvelope,
    "bootstrap_plan.schema.json": BootstrapPlan,
    "bootstrap_receipt.schema.json": BootstrapReceipt,
    "compiled_project_manifest.schema.json": CompiledProjectManifest,
    "compiled_repository_map.schema.json": CompiledRepositoryMap,
    "command_result.schema.json": CommandResult,
    "diagnostic_snapshot.schema.json": DiagnosticSnapshot,
    "domain_project_manifest.schema.json": ProjectManifest,
    "domain_state_transition.schema.json": DomainStateTransition,
    "event_envelope.schema.json": EventEnvelope,
    "migration_catalog.schema.json": MigrationCatalog,
    "migration_record.schema.json": MigrationRecord,
    "project_gap_report.schema.json": ProjectGapReport,
    "project_intake_request.schema.json": ProjectIntakeRequest,
    "project_profile_detection.schema.json": ProjectProfileDetection,
    "project_state.schema.json": ProjectStateRecord,
    "requirement_record.schema.json": RequirementRecord,
    "repository_discovery.schema.json": RepositoryDiscovery,
    "runtime_configuration.schema.json": RuntimeSettings,
    "secret_reference.schema.json": SecretReference,
    "state_transition.schema.json": StateTransition,
    "task_state.schema.json": TaskStateRecord,
    "traceability_link.schema.json": TraceabilityLink,
    "traceability_mutation.schema.json": TraceabilityMutation,
    "traceability_mutation_result.schema.json": TraceabilityMutationResult,
}


def rendered_schemas() -> dict[str, dict[str, Any]]:
    result: dict[str, dict[str, Any]] = {}
    for filename, model in sorted(SCHEMA_MODELS.items()):
        schema = model.model_json_schema(mode="validation")
        schema["$schema"] = "https://json-schema.org/draft/2020-12/schema"
        schema["$id"] = f"https://project-pipeline.local/schemas/{filename}"
        result[filename] = schema
    return result


def write_schemas(root: Path) -> dict[str, str]:
    target = root / "schemas"
    target.mkdir(parents=True, exist_ok=True)
    result: dict[str, str] = {}
    for filename, schema in rendered_schemas().items():
        path = target / filename
        path.write_text(
            json.dumps(schema, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
            encoding="utf-8",
            newline="\n",
        )
        result[filename] = path.relative_to(root).as_posix()
    return result


def validate_schemas(root: Path) -> list[str]:
    errors: list[str] = []
    for filename, schema in rendered_schemas().items():
        path = root / "schemas" / filename
        if not path.exists():
            errors.append(f"missing generated schema: schemas/{filename}")
            continue
        try:
            observed = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as error:
            errors.append(f"invalid generated schema schemas/{filename}: {error}")
            continue
        if observed != schema:
            errors.append(f"stale generated schema: schemas/{filename}")
    return errors
